# site settings
title: Stephanie Pakrul
subtitle: portfolio
email: stephthegeek@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 3491 20th St
city: San Francisco
state: CA
zip_code: 94110
country: United States of America
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 30

# contact form settings
form_url: https://formspree.io/stephthegeek@gmail.com # endpoint URL to receive contact form submissions
form_email_name: _replyto # value of the "name" attribute in the "email" field

# social settings
500px_url: https://500px.com/stephthegeek
facebook_url: https://www.facebook.com/stephthegeek
github_url: https://github.com/stephthegeek
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/stephthegeek/
linkedin_url: https://www.linkedin.com/in/stephthegeek/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
